### PR TITLE
merge forks

### PR DESCRIPTION
**Pull request by zxbodya**
combined work done in forks by:

- @steelbrain merged in 62d53d094a418e41c2e84d546deb244d83698da9
- @rgoldfinger-quizlet merged in b6682fd2fbe6147e39769498702d012c68d15e2f
- @jmhain merged in 1660a3313a031ace292d3c2690ad8142ba8db5f8
- @CureApp merged in d914fcd909058b71ffaead1b219de8ee7326f8b9

---

To make it possible, did some changes before and after merging:

- added prettier with config from @steelbrain branch (because there were most of the changes to be merged), applied it everywhere before the merge
- fixed lint errors, configured prettier integration with eslint
- added npm script for  checking code coverage
- updated dependencies
- used proper typings where available, fixed typing issues found
- removed unused dependencies
- updated circleci configs added in @CureApp fork, to use npm instead of yarn, added [codecov.io](http://codecov.io) integration

---

hope - it will help to have more collaboration in the main repository

### CODE REVIEW

**Comment by Kiikurage** [comment]
Amazing! Thank you so much!! I'll check tonight!

**Comment by steelbrain** [comment]
Fyi, there's one "bug" in the current `declare functions` converter that I hadn't fixed. For `export declare function...` it does not copy over the `export` part

**Comment by Kiikurage** [comment]
@steelbrain, @rgoldfinger-quizlet, @jmhain, @CureApp. I haven't cheked the detail of code yet, but if it's not good to merge your code to this repository, please feel free to tell me.

**Comment by steelbrain** [comment]
Everything from my repository should be good to merge, I've already tested it on a couple hundred LOCs, worked flawlessly. Only known bug is what I've mentioned above

**Comment by Kiikurage** [comment]
@steelbrain Thanks! I'll fix that problem.

**Comment by zxbodya** [comment]
@Kiikurage

if planning to do anything big - I started some refactoring(https://github.com/zxbodya/babel-plugin-flow-to-typescript/pull/1), which might be interesting to check/merge first

It is about cleaning up type conversion, and decoupling them from `NodePath`, also affects transformations related to a function declarations.

Generally - it is good, but at the moment there are regressions about optional arguments in function declaration (https://github.com/zxbodya/babel-plugin-flow-to-typescript/pull/1/files#diff-752d405e527bcc958f61ca56d295bc7aR206). Which, I think, should be done differently - instead of having `NullableTypeAnnotation` logic to be aware of function declaration(by traversing to parent `NodePath`), function declaration should be aware of optional types and to encapsulate all related logic

**Comment by zxbodya** [comment]
finished refactoring I mentioned above, briefly about changes:

refactoring:


- bugfix, additional tests
- in multiple places added code to preserve comments (by copying then from an original node into converted where needed)
- cleanup: removing not needed typecasts, @ts-ignores, splitting some things into separate files, extracting shared code, etc…

features:

- changed converters to restrict them to use only Node not NodePath wrapping it
- added visitor to verify that all Flow related nodes were converted, otherwise - throw an error
- removed some ts-ignores
- split TypeAlias and TypeAnnotation to separate visitors
- convert type instantiation in call expressions
- add .editorconfig
- new visitors
   - FunctionDeclaration
   - DeclareVariable
   - DeclareTypeAlias
   - DeclareInterface
   - DeclareModule
   - DeclareModuleExports
   - DeclareOpaqueType
   - DeclareExportDeclaration
   - NewExpression
   - ArrowFunctionExpression
   - improvements for existing visitors

btw, issue about declaring function exports should also be fixed

**Comment by steelbrain** [comment]
Been testing this branch, here's some fixes I've gathered up:

To fix computed string literals:

```diff
diff --git a/src/converters/convert_member_expression.ts b/src/converters/convert_member_expression.ts
index dae1964..48da39e 100644
--- a/src/converters/convert_member_expression.ts
+++ b/src/converters/convert_member_expression.ts
@@ -23,7 +23,7 @@ function getMemberExpression(members: MemberType[]): MemberType {
   return memberExpression(
     members.length === 1 ? members[0] : getMemberExpression(members),
     lastMember,
-    lastMember!.type === 'NumericLiteral',
+    lastMember!.type.endsWith('Literal'),
   );
 }
 function getConditionalExpression(members: MemberType[], index: number): ConditionalExpression {
```

To add support for Class Expressions (ie. `somefunc(class extends Another<Type> {}`)

```diff
diff --git a/src/index.ts b/src/index.ts
index fc65053..9cdcaa6 100644
--- a/src/index.ts
+++ b/src/index.ts
@@ -37,6 +37,7 @@ const visitor: Visitor = {
   ClassMethod,
   DeclareClass,
   ClassDeclaration,
+  ClassExpression: ClassDeclaration,
   ExportNamedDeclaration,
   InterfaceDeclaration,
   OptionalMemberExpression,
diff --git a/src/visitors/class_declaration.ts b/src/visitors/class_declaration.ts
index 3d9c2b2..ec3d121 100644
--- a/src/visitors/class_declaration.ts
+++ b/src/visitors/class_declaration.ts
@@ -1,5 +1,6 @@
 import {
   ClassDeclaration,
+  ClassExpression,
   isTypeParameterInstantiation,
   isTypeParameterDeclaration,
   ClassImplements,
@@ -10,7 +11,7 @@ import { convertInterfaceExtends } from '../converters/convert_interface_declara
 import { convertTypeParameterInstantiation } from '../converters/convert_type_parameter_instantiation';
 import { convertTypeParameterDeclaration } from '../converters/convert_type_parameter_declaration';

-export function ClassDeclaration(path: NodePath<ClassDeclaration>) {
+export function ClassDeclaration(path: NodePath<ClassDeclaration | ClassExpression>) {
   const node = path.node;

   const superTypeParameters = node.superTypeParameters;
```

**Comment by zxbodya** [comment]
added fixes, @steelbrain mentioned

Also, rebased other improvements I did recently:

1. Adjusted code to preserve comments in more places, added additional logic to support `recast` if it is used (copying `comments` field on a node)
2. Adjusted logic related for declare statement, to remove `declare` keyword inside of module
3. Updated object type annotation conversion logic to properly handle method declarations
4. Updated declare export visitor to support more cases

About recast - generally, it is working very well, but there is small bug about type parameters in expressions  https://github.com/benjamn/recast/pull/613

---

Also, I started a project to provide a cli for converting flow to ts - https://github.com/zxbodya/flowts
It uses my fork of babel plugin and fork with the fix for recast, also it is planned to provides features that are out of the scope of this plugin (not related to syntax, but about updating code itself like adding imports or renaming flow type names to corresponding names in typescript)

You can try it with recast `flowts --recast ./path/to/src` -- it looks much better comparing to babel in terms of preserving original code formatting.

**Comment by Kiikurage** [comment]
I'm so sorry for too late reply. I merged this

**Pull request merged**
